### ISSUE TITLE
Delete and move descendants one level up not working

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/ThesauRex#124]
### Steps to reproduce
1. Try to delete a concept and chose option: *... and move descendants one level up*

### Expected behaviour
The concept should be deleted.

### Actual behaviour
The following error occurred:

`An error occurred SQLSTATE[23503]: Foreign key violation: 7 ERROR: insert or update on table "th_broaders" violates foreign key constraint "th_broaders_broader_id_foreign"<br/> DETAIL: Key (broader_id)=(-1) is not present in table "th_concept". (SQL: insert into "th_broaders" ("broader_id", "narrower_id") values (-1, 12)) 
`

javascript console log: `Something went wrong...`

**Comment by v1r0x** [comment]
Does this happen for all concepts or just top-level concepts or not top-level concepts?

**Comment by dirkseidensticker** [comment]
It works for normal concepts but not if the descendants would become top-level concepts. Is that by design?
