### ISSUE TITLE
Broader and Narrower won't be displayed if German language file isn't there

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/ThesauRex#128]
If - like in PotCat - only the English language file exists ThesauRex won't be display broader and narrower contexts. The Search is also effected by this issue.

**Comment by v1r0x** [comment]
Just to clarify: It is not about a file, but the concepts. If a concept has only english (or any other non-german) labels, they don't appear in the search or broader/narrower box. This is, because the language defaults to german if none is present.
