### ISSUE TITLE
Enable Drag & Drop checkbox is missing!

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/ThesauRex#136]
![screenshot 2018-02-21 11 07 38](https://user-images.githubusercontent.com/6630811/36474351-8e513d18-16f7-11e8-9752-f4acc69ee3f8.png)

Since the Material Design change the checkbox for Drag&Drop is missing. Clicking on the label still works but you wouldn't know at what state it is.

**Comment by v1r0x** [comment]
It's not missing, actually :wink:  But yes, it is overlayed somehow...
Thanks for the report!

**Comment by v1r0x** [comment]
In the new vue-version of ThesauRex this checkbox has been removed and I don't think it is really needed? Thus, I'd like to close this issue if you are ok with that @dirkseidensticker ?

**Comment by dirkseidensticker** [comment]
So now you can drag&drop by default?

**Comment by v1r0x** [comment]
Yes, it is enabled by default

**Comment by dirkseidensticker** [comment]
👍
