### ISSUE TITLE
Delete element

### ISSUE THREAD

**Issue by v1r0x** [eScienceCenter/ThesauRex#15]
There should be three variants of deleting an element
- [x] Delete element and all its descendants
- [x] Delete element and move all descendants one level up
- [x] Delete element and move all descendants to the top level

**Comment by derntl** [comment]
The three variants are only relevant if the element has children. If not, a simple delete menu item suffices.

**Comment by v1r0x** [comment]
I added a second _Delete_ option in the context menu. With the context menu plugin it is not possible to dynamically display/hide elements in the menu.

**Comment by v1r0x** [comment]
> With the context menu plugin it is not possible to dynamically display/hide elements in the menu

Seems that it **is** possible. Added another commit with a dynamic context menu.

**Comment by derntl** [comment]
👍
