### ISSUE TITLE
Search should scroll to first hit

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/ThesauRex#27]
When searching, matching subtrees are expanded. The first hit should be visible, so auto scroll there

**Comment by derntl** [comment]
Cannot test this, because the search itself seems to be broken again. The wrong subtrees are expanded most of the time, e.g. when searching for Kaserne oder Palisade.

**Comment by v1r0x** [comment]
Should this be fixed in this branch as well?

**Comment by derntl** [comment]
it is fine if it gets fixed in some pull request. i am not sure what branch the live version on our server reflects

**Comment by v1r0x** [comment]
We're now on `scroll-to-result` again.
