### ISSUE TITLE
Import/Export

### ISSUE THREAD

**Issue by v1r0x** [eScienceCenter/ThesauRex#31]
Currently there is no proper import and export functionality. Currently I'm using two python scripts, but one has to set the database connection values as hardcoded string in the file or as parameter. If we only want one function/script for all instances we should either call the script from php and get the values from the `.env` file or re-implement it in php. First solution would be easier, but it is a bit ugly...
Nethertheless we need the following functionality:
- [x] Import tree
  - [x] leave existing concepts as they are + add new concepts from the upload
  - [x] update existing concepts based on the upload + add new concepts from the upload
  - [x] purge all existing concepts + add new concepts from the upload
- [x] Export tree
  - [x] Export selected element and it's descendants
- [x] Disable GUI during import/export (because it takes long)

**Comment by v1r0x** [comment]
There are a couple of php libraries for parsing rdf files
1. [EasyRDF](http://www.easyrdf.org/)
2. [DOM](http://php.net/manual/de/class.domdocument.php)
3. [SimpleXML](http://php.net/manual/de/book.simplexml.php)

Any preference? @derntl

**Comment by v1r0x** [comment]
I started working with EasyRDF, because it already has all the logic for rdf files. Starting something new would result in a lot of debugging and may not be compatible with other software.

**Comment by v1r0x** [comment]
As mentioned in #46 the import wipes the whole database and inserts the data from the rdf file. Is this the desired behaviour or should the code instead update existing entries and add missing ones? @eScienceCenter/spacialists

**Comment by derntl** [comment]
@AngusLeBoeuf @dirkseidensticker  please answer the last comment.

**Comment by derntl** [comment]
during import and or export (takes long) the gui should be disabled (loading pizza at top level)

**Comment by derntl** [comment]
Not all aspects fixed by PR #46

**Comment by dirkseidensticker** [comment]
@v1r0x @derntl Generally speaking a more subtle behavior would be preferential. Good options could be:

A. leave existing concepts as they are + add new concepts from the upload
B. update existing concepts based on the upload + add new concepts from the upload
C. purge all existing concepts + add new concepts from the upload

**Comment by v1r0x** [comment]
@dirkseidensticker I added your options to OP. Am I right that C. is the current (default) behaviour?

**Comment by dirkseidensticker** [comment]
@v1r0x Yes, I think C should be default.
