### ISSUE TITLE
Expanding to the search result sometimes expands the wrong subtrees

### ISSUE THREAD

**Issue by v1r0x** [eScienceCenter/ThesauRex#42]
see discussion in #33

**Comment by v1r0x** [comment]
This may be fixed with the working drag and drop support.
The tree has been resetted with our current master tree. If it still doesn't work, it is a bug, otherwise we can close this issue.

Please test @eScienceCenter/spacialists

**Comment by dirkseidensticker** [comment]
I never got this issue.
