### ISSUE TITLE
changes to a concept not reflected in all subtrees

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/ThesauRex#51]
Take a concept _A_ that appears in multiple locations in the tree. When i add a new narrower concept _B_ to _A_, this new concept _B_ is not reflected in all locations of _A_ in the tree.

**Comment by v1r0x** [comment]
I'm currently working on this one and the results looking good for
- Context menu > Add new concept
- Add broader concept
- Add narrower concept

But what should happen after one deletes a concept using the options from the context menu?
1. Delete concept and descendants
2. Delete concept and move descendants one level up
3. Delete concept and move descendants to the top level

My idea for 1. was to remove the concept completely, which would be easy to implement. But I couldn't think of a good behaviour for 2. and 3. Do you have any idea @dirkseidensticker @AngusLeBoeuf ?

**Comment by dirkseidensticker** [comment]
As there are hypothetical use cases for this, I would suggest the following:

* in any case there should be a warning, stating that deleting a concept that has multiple broader or narrower concepts results in the following ...
* this warning must be accepted "'yes' i will delete them'
* cases:
  * 1. is good as you proposed
  * 2. should only work on the selected element in the tree (the one you clicked)
  * 3. is not necessary  and can be removed

**Comment by v1r0x** [comment]
I encountered several problems with our ideas.

One problem is your case 2 for an element as 'Textilverarbeitung'.
### Example
- Path 1: `Fund > Artefakt > Form > Werkzeug > Textilverarbeitung`
- Path 2: `Facetten > Artefakt (thematisch) > Werkzeug > Textilverarbeitung`
It has only one parent ('Werkzeug'), but 'Werkzeug' has two parents. Thus, moving the children of 'Textilverarbeitung' in Path 1 would move them in Path 2 as well.

Another problem is ('Textilverarbeitung' again) that the current implementation for an element with one parent, but two parents can not compute the exact path to this element in the tree.

We should discuss this in person next week.

**Comment by v1r0x** [comment]
Thanks to #63 I think this has been fixed. Can someone confirm this please? @eScienceCenter/spacialists

**Comment by derntl** [comment]
🎱
