### ISSUE TITLE
typing in the search-bar is impossible after clicking on a box-button

### ISSUE THREAD

**Issue by AngusLeBoeuf** [eScienceCenter/ThesauRex#59]
search-bar doesn't work after selecting - let's say - the import-button!

**Comment by v1r0x** [comment]
This was a bug in the `angular-boostrap` package. A `bower update` fixed this problem. Could you confirm this @AngusLeBoeuf ?

**Comment by AngusLeBoeuf** [comment]
Right! Now it is working!

**Comment by derntl** [comment]
🎱 🎉
