### ISSUE TITLE
no pref/alt labels after drag&drop

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/ThesauRex#79]
drag a concept from the master to the project tree. in the concept details, no detail is shown (broaders, narrowers, alt, pref all empty)

**Comment by v1r0x** [comment]
Works fine for me on master. Maybe this has been fixed in one of the other PRs?

**Comment by derntl** [comment]
👍

**Comment by derntl** [comment]
Now it appeared again, try on demo/atlantis/thesaurex, which is on master branch. After refresh children are gone
