### ISSUE TITLE
add child concept

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/ThesauRex#81]
add a concept under a top level concept. nothing happens visually, after reload i see it was added.

not sure by the way how the "Enable Editing" checkbox affects the delete & add concepts operations. Even if the checkbox is unckecked, I can remove concepts, add concepts.

So when "Enable Editing" is off, it should not be possible to do anything but does this make sense? What was the idea of this checkbox again? If it stays, it needs to prevent any edit. If it only affects drag & drop edits, it should be relabeled to reflect this.

**Comment by v1r0x** [comment]
The checkbox only affects drag&drop editing. It was added to switch between "project view" and "admin view". As soon as we have proper handling of these views we can remove it.

**Comment by derntl** [comment]
ok so then let's make this an enhancement for Babylon

**Comment by v1r0x** [comment]
> add a concept under a top level concept. nothing happens visually, after reload i see it was added.

Do you mean add (a new element) or drag&drop? adding new elements works fine for me (except for a bug I found).

**Comment by v1r0x** [comment]
Do we still need this? Is there a problem with adding a child concept or is this issue about the checkboxes and protected master tree? If it is about the checkboxes and protected tree we should close this one in favor of #86

**Comment by derntl** [comment]
okay, covered by #86
