### ISSUE TITLE
add concept and then narrowers fails

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/ThesauRex#84]
* add a new concept
* in the new concept details, add a narrower concept using the "Narrower Concepts" box on the right-hand side
* The result is that the concept is created, but not shown in the GUI and in the console we see an error `Error: main.tree[treeName].concepts[parentId] is undefined`

**Comment by v1r0x** [comment]
I can not reproduce this. Could you please test again? @derntl

**Comment by derntl** [comment]
The problem has disappeared
