### ISSUE TITLE
separate master/project thesauri

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/ThesauRex#86]
after #85 is implemented we must proceed to have permissions protected master tree in all thesaurex instances, and a project-local tree.

**Comment by v1r0x** [comment]
For feedback see info in #102

**Comment by derntl** [comment]
Is the label `discussion` on this still reasoanble?

**Comment by derntl** [comment]
As discussed in the meeting today:
* We discard the idea of an external Master Thesaurus
* We rename Master Thesaurus to something that indicates that it is a Sandbox tree for import/export, playing around, etc.
* The Sandbox tree is not visible usually. It needs to be activated some way (e.g. via some menu or a toggle)
