### ISSUE TITLE
when creating a new concept, its parent should be expanded

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/ThesauRex#89]
...if it is not expanded already

**Comment by derntl** [comment]
Sorry have to reopen. It expands only when new subconcept created via the context menu in the tree. Should also expand when new subconcept is created via Narrower Concepts

**Comment by v1r0x** [comment]
I think this is another use case. If you want to add several existing narrowers, one has to search for it, add it, re-select the parent, search for another, ...

**Comment by derntl** [comment]
Okay but if I create a new narrower, then the new narrower is the new concept that is active in the editor, but it is not shown or highlighted in the tree unless I expand manually.
