### ISSUE TITLE
sorting of child contexts

### ISSUE THREAD

**Issue by derntl** [eScienceCenter/ThesauRex#94]
child contexts are seemlingy sorted randomly. there seem to be 2 orders: the leafs appear in order and the contexts with children too, but there is no overall order.

**Comment by v1r0x** [comment]
Moved to backlog. Tried to fix this, but it is not that easy. Maybe we should try it together @derntl

**Comment by v1r0x** [comment]
Fixed in current working branch. Will be in next release (v0.9 aka Isfahan)
